### ISSUE TITLE
Adding Z Search Interface generates Internal Server Error

### ISSUE THREAD

**Issue by wlang42** [zopefoundation/Products.ZSQLMethods#46]
### What I did:

* Added a ZSQLMethod `fullname_sql` with
  `select 'Willi Langenenberger' FULLNAME from dual`

* Tested it with the "Test" tab

![zsearch-02](https://github.com/zopefoundation/Products.ZSQLMethods/assets/22004097/e52a3ee2-eaea-4e91-9085-4145a4e9f911)

* Filled in the "Add Search Interface" form

![zsearch-03](https://github.com/zopefoundation/Products.ZSQLMethods/assets/22004097/1097d1ba-6a34-4868-aaa1-c66d14034e58)

### What I expect to happen:

* The Search Interface to be added

### What actually happened:

* Boom:

![zsearch-04](https://github.com/zopefoundation/Products.ZSQLMethods/assets/22004097/5074c724-e6ed-4931-ab71-546acf13bedf)

### What version of Python and Zope/Addons I am using:

Zope-5.9
Python-3.9.5
Products.ZSQLMethods-4.0

### Additional Info:

* Error message in Log:
```
ValueError: The input searchable object, <em>fullname_sql</em>,
                has not been tested.  Until it has been tested,
                it's output schema is unknown, and a report
                cannot be generated.  Before creating a report
                from this query, you must try out the query.  To
                try out the query, <a href="https://.../fullname_sql">click here</a>.
```

* Full Traceback:

```
2023-12-30 21:09:37,860 ERROR   [waitress:435][waitress-0]
 Exception while serving /VirtualHostBase/https/bach.wu.ac.at:443/VirtualHostRoot/_vh_zope4/_vh_prod2/wlang/manage_addProduct/ZSQLMethods/manage_addZSearch
Traceback (most recent call last):
  File "/opt/wu-wien/zope/buildouts/z5-dev-wl/eggs/waitress-2.1.2-py3.9.egg/waitress/channel.py", line 428, in service
    task.service()
  File "/opt/wu-wien/zope/buildouts/z5-dev-wl/eggs/waitress-2.1.2-py3.9.egg/waitress/task.py", line 168, in service
    self.execute()
  File "/opt/wu-wien/zope/buildouts/z5-dev-wl/eggs/waitress-2.1.2-py3.9.egg/waitress/task.py", line 434, in execute
    app_iter = self.channel.server.application(environ, start_response)
  File "/opt/wu-wien/zope/buildouts/z5-dev-wl/eggs/Paste-3.7.1-py3.9.egg/paste/translogger.py", line 77, in __call__
    return self.application(environ, replacement_start_response)
  File "/opt/wu-wien/zope/buildouts/z5-dev-wl/eggs/Zope-5.9-py3.9.egg/ZPublisher/httpexceptions.py", line 30, in __call__
    return self.application(environ, start_response)
  File "/opt/wu-wien/zope/buildouts/z5-dev-wl/eggs/Zope-5.9-py3.9.egg/ZPublisher/WSGIPublisher.py", line 391, in publish_module
    response = _publish(request, new_mod_info)
  File "/opt/wu-wien/zope/buildouts/z5-dev-wl/eggs/Zope-5.9-py3.9.egg/ZPublisher/WSGIPublisher.py", line 285, in publish
    result = mapply(obj,
  File "/opt/wu-wien/zope/buildouts/z5-dev-wl/eggs/Zope-5.9-py3.9.egg/ZPublisher/mapply.py", line 98, in mapply
    return debug(object, args, context)
  File "/opt/wu-wien/zope/buildouts/z5-dev-wl/eggs/Zope-5.9-py3.9.egg/ZPublisher/WSGIPublisher.py", line 68, in call_object
    return obj(*args)
  File "/opt/wu-wien/zope/buildouts/z5-dev-wl/develop-source/Products.ZSQLMethods/src/Shared/DC/ZRDB/Search.py", line 63, in manage_addZSearch
    raise ValueError(
ValueError: The input searchable object, <em>fullname_sql</em>,
                has not been tested.  Until it has been tested,
                it's output schema is unknown, and a report
                cannot be generated.  Before creating a report
                from this query, you must try out the query.  To
                try out the query, <a href="https://.../fullname_sql">click here</a>.
```

**Comment by wlang42** [comment]
There a two things with that:

* The error message should make it to the user interface

* In that specific case, the error message is wrong (and misleading). It says that the ZSQL Method is not tested, which is not the case.

Addressing the second point: The Search Interface needs the `_col` Attribute of the searchable object (ie ZSQL Method), which is assumed to be created when using the "Test" tab for it.

But, the "Test" tab does not create the `_col` attribute anymore.

It is created only, if the `Shared.DC.ZRDB.DA.DA.__call__` method is called with the `test__` argument set to a `True` like value. But thats currently not the case when called from `DA.manage_zmi_test`.
